### ISSUE TITLE
✍🏼 Blog: Creating your first Backstage backend plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/janus-idp.github.io#11]
## Goal
Post a blog on janus-idp.io which provides guidance on how a Platform Engineer can create their first Backstage backend plugin

**Comment by relessawy** [comment]
@serenamarie125 I would like to volunteer for this one.

**Comment by serenamarie125** [comment]
Terrific! I've assigned the issue to you, to ensure no one else will work on it.  Let me know when you have something to review! 
Thanks for taking this on @relessawy !

**Comment by Alok650** [comment]
Hi guys, Is there an update on this blog? was this created?
