### ISSUE TITLE
✍🏼 Blog: Introducing our new Quay plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/janus-idp.github.io#14]
## Goal

Post a blog on janus-idp.io introducing our new Quay plugin!

**Comment by tumido** [comment]
I have a draft available here:

https://docs.google.com/document/d/1w9mxg41I84Eu8I2Txc2qe0_qx4SuuYxvUNCXCZ1KwOQ/edit?usp=sharing

PTAL, I would love some feedback. :slightly_smiling_face:
