### ISSUE TITLE
Create contributors guide

### ISSUE THREAD

**Issue by myfear** [janus-idp/janus-idp.github.io#18]
Essential for community members to know where to get started and how to set up the Janus Showcase locally.
Could be enhanced with explanation of the individual plugins and how they are architected.

**Comment by christophe-f** [comment]
It's a first step. Can find more information here:
https://github.com/janus-idp/backstage-showcase
https://github.com/janus-idp/backstage-showcase/blob/main/docs/getting-started.md

**Comment by jasperchui** [comment]
Resolved by https://github.com/janus-idp/backstage-plugins/issues/204
