### ISSUE TITLE
The Nexus plugin is not visible from the plugin page

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/janus-idp.github.io#247]
A user/customer should be able to find the Nexus plugin on the janus-idp.io website.

We should also create a PR to display the Nexus plugin on backstage.io

**Comment by Zaperex** [comment]
Is there a specific icon we should be using for the nexus plugin?

**Comment by christophe-f** [comment]
Same icon as ACR, Jfrog Artifactory
