### ISSUE TITLE
Add YouTube link in header

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/janus-idp.github.io#43]
![image](https://user-images.githubusercontent.com/7453394/222131737-dae947e9-c6b5-4f30-af71-6c9795d06a46.png)

_Originally posted by @tumido in https://github.com/janus-idp/janus-idp.github.io/pull/33#discussion_r1121593295_

**Comment by kclibrarian** [comment]
I can complete this ticket if it's still open.

**Comment by christophe-f** [comment]
Thanks that would be awesome.
