### ISSUE TITLE
Add a tag filtering mechanism to the plugin page

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/janus-idp.github.io#83]
## Background

Currently the [plugin page](https://janus-idp.io/plugins) displays all plugins regardless of the plugin role specified in its `package.json`. e.g. [3scale-backend](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/3scale-backend/package.json#L13)

## Enhancement

- Instead of using the `role` property, add a `tags` property in the plugin's `package.json`. This is because the `role` property is not easily understandable i.e. a custom action has a role of `backend-plugin-module`
- Create a tag filtering mechanism based on the plugin role
- Create a search bar based on the plugin name and tags

**Comment by serenamarie125** [comment]
Acceptance Criteria:

1. remove "Learn more" link
2. make the description left aligned
3. add tags to the bottom of the card, have them left-aligned

Tags should include:
1. Frontend
2. Backend
3. Custom Actions

**Comment by gorkem** [comment]
One correction, If `role` refer to the `backstage.role` on `package.json`.  We can not add tags _instead of_ `role` but in _addition to_ `role`. As `backstage.role` has significance to backstage build process.

**Comment by schultzp2020** [comment]
> One correction, If `role` refer to the `backstage.role` on `package.json`. We can not add tags _instead of_ `role` but in _addition to_ `role`. As `backstage.role` has significance to backstage build process.

Whoops, maybe I should've clarified that. I was not planning on removing the `role` property.

**Comment by tumido** [comment]
Updating with a chat convo on this:

@christophe-f:
> We could just add the tag in the PLUGINS_LIST constant. That will avoid to syncup and read all the package.json files, and add website specific content into the plugins (edited) 

@tumido:
> That makes sense... and it's not like tags for a plugin are gonna change anyways...

@schultzp2020:
> So should we add the tags here? https://github.com/janus-idp/janus-idp.github.io/blob/main/apps/website/content/plugin-list.js#L19-L27

@christophe-f:
> yes that would be much easier.

**Comment by AayushSaini101** [comment]
@schultzp2020 Can I work on this issue?

**Comment by schultzp2020** [comment]
@AayushSaini101 sorry, there is already an existing [pr](https://github.com/janus-idp/janus-idp.github.io/pull/90) to fix this issue.
